version: '3.8'

services:
  mpsc-app:
    build:
      context: .
      args:
        # इमेज बिल्ड होताना लागणाऱ्या कीज (Vite साठी)
        - ARG VITE_SUPABASE_URL=https://vswtorhncwprbxlzewar.supabase.co
        - ARG VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzd3RvcmhuY3dwcmJ4bHpld2FyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzNzI2NDUsImV4cCI6MjA4NTk0ODY0NX0.0V9-6ZX6dZ7bYQ_P8DYJkuFmYaCEQ>
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    container_name: mpsc_online_app
    ports:
      - "8080:3000" # बाहेरून ८०८० पोर्टवर वेबसाईट दिसेल
    env_file:
      - .env        # सर्व सिक्रेट कीज (Groq, Admin Key) इथून घेतल्या जातील
    restart: unless-stopped
    networks:
      - mpsc-network

networks:
  mpsc-network:
    driver: bridge
