name: Deploy to Oracle Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}      
          username: ${{ secrets.USERNAME }} 
          key: ${{ secrets.SSH_KEY }}     
          script: |
            cd /home/ubuntu/mpsc.online
            # १. जुने सर्व लोकल बदल काढून नवीन कोड घेणे
            git fetch origin main
            git reset --hard origin/main
            
            # २. डॉकर सर्विसेस रिस्टार्ट करणे (नवीन 'docker compose' कमांडसह)
            docker compose down
            docker compose up -d --build --remove-orphans
